
version: "3.9"

x-disabled:

services:

  configure-db-oneshot:
    container_name: phoebus-archiver-configure-db-oneshot
    image: docker.io/pklaus/phoebus-archiver:e69a776
    volumes:
      - ./settings.ini:/settings.ini:ro
      - ./Example.xml:/Example.xml:ro
    links:
      - db
    networks:
      - phoebus-archiver
    command: -engine Example -import /Example.xml -port 4812 -replace_engine -settings /settings.ini

  app:
    container_name: phoebus-archiver-app
    image: docker.io/pklaus/phoebus-archiver:e69a776
    #restart: unless-stopped
    ports:
      - "4812:4812"
    links:
      - db
      - example-ioc
    depends_on:
      - db
    volumes:
      - ./settings.ini:/settings.ini:ro
    stdin_open: true
    tty: true
    #command: "-help"
    networks:
      - phoebus-archiver
    command: -engine Example -port 4812 -settings /settings.ini

  db:
    container_name: phoebus-archiver-db
    image: postgres:13.3
    #restart: unless-stopped
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - phoebus-archiver
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dA8pML9bv1By

  example-ioc:
    container_name: phoebus-archiver-example-ioc
    image: pklaus/epics_base:7.0.4_debian
    stdin_open: true
    tty: true
    working_dir: /epics/iocs/example/iocBoot/iocEXAMPLE
    expose:
      - "5064-5065/udp"
      - "5064-5065"
    networks:
      - phoebus-archiver
    restart: unless-stopped
    command: ./st.cmd

volumes:
  db-data:
networks:
  phoebus-archiver:
